.TH IJKDIFFTABLE 1 "16 MAY 2008"
.SH NAME
ijkdifftable \- output the difference of two isosurface tables
.SH SYNOPSIS
.B ijkdifftable 
.RB "[\-h]"
{file1} {file2}
.SH DESCRIPTION
.B ijkdifftable
is a program to output the difference in polyhedra and in table
entries of two isosurface tables.
.B ijkdifftable
halts if the tables have different dimensions
or if the polyhedra have different vertices or edges.
It does not halt if the polyhedra have different facets,
or the table entries are different.
.B ijkdifftable
ignores the simplex order in table entries
and ignores the vertex order in comparing isosurface simplices.
.SH OPTIONS
.TP
.BR \-h
Print help message (and exit.)
.SH NOTES
In comparing two isosurface simplices,
the vertex orders may imply different simplex orienations but 
.B ijkdifftable
will not recognize this as a difference.
.SH "SEE ALSO"
.BR ijkgentable, ijktable(3), xit(5).
.SH AUTHOR
Rephael Wenger


